### ISSUE TITLE
Operation

### ISSUE THREAD

**Issue by YashAndonia** [Denver-Pinto/findme-ds#9]
Is this the entire Project? How do I operate it and which files do I operate from?

**Comment by Denver-Pinto** [comment]
You'll need XAMPP for Apache and MySQL purposes.
Copy all the files to the XAMPP ->htdocs folder.
Start Apache and MySQL in XAMPP Control Panel
Run the config.php on browser before the website (localhost/config.php)
Run the home.php to enter the website(localhost/home.php)
